version: "3"
services:
    db_server:
        build: ./db
        container_name: postgre-db
        restart: always
        environment:
            - POSTGRES_PASSWORD=1234
            - POSTGRES_USER=dev_user
        expose:
            - 5432
        healthcheck:
            test: exit 0
    book_app:
        build:
            context: .
            dockerfile: Dockerfile.dev
        container_name: book-app
        environment:
            - ENV_CONFIG=settings.settings.DevelopmentConfig
            - DB_CONNECTOR=postgresql
            - DB_USER=dev_user
            - DB_PASS=1234
            - DB_HOST=db_server
            - DB_NAME=book_db
            - WAIT_HOSTS=db_server:5432
        volumes: 
            - ./project:/app/project
        entrypoint:
            sh -c "/wait && python /app/project/manage.py db upgrade && python /app/project/server.py"
        depends_on:
            - db_server
        ports:
            - "8000:5000"
        restart: on-failure
        stdin_open: true
        tty: true
