FROM python:3.6-alpine

# Add dependencies to install uwsgi
RUN apk add python3-dev build-base linux-headers pcre-dev gcc


WORKDIR /app
COPY ./requirements.txt .
RUN pip install -r requirements.txt

EXPOSE 5000
COPY ./project ./project
COPY ./server.ini .

COPY ./migrations ./migrations
RUN python ./project/manage.py db migrate
RUN python ./project/manage.py db upgrade

ENTRYPOINT [ "python" ]
CMD ["./project/server.py"]
